### ISSUE TITLE
description of Figure 2 in demos/invasive-species

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-docs#25] opened 2018-02-26 13:10 UTC
- the image contains textual description which should be written as text in markdown.
- the image contains "Fig 3." although it is used as "Figure 2" in markdown

see Figure 2:
http://localhost:8000/demos/invasive-species/#3-visualization

**Comment by HannesLUBW** [comment] 2018-02-28 14:29
Hi Viliam,
the graph was provided by Daniel. Therefore I also assigned the task to him. I moved the textual description of the figure towards the markdown.

**Comment by HannesLUBW** [comment] 2018-02-28 14:35
From my side the issue is closed now. Just waiting for Daniel to confirm my changes and to close the issue.

**Comment by IdealOutage** [comment] 2018-02-28 15:08
Yes, the image contained textual description and was therefore falsely labeled as Fig. 3. Thank you for changing this @HannesLUBW !

**Closed as completed by IdealOutage** 2018-02-28 15:08 UTC
Labels: bug
